# Site settings
title: Airbel
email: dev@ocupop.com
description: 'The Airbel Center is the innovation center at the International Rescue Committee. We design, test, and drive large-scale adoption of innovations for people affected by crisis, focusing on projects that have the potential for reaching the most people with the most effective breakthrough products, services, and systems.'
url: "https://icy-ship.cloudvent.net"
permalink: pretty
# analytics_code:

placeholders:
  hero: https://via.placeholder.com/1800x500?text=Hero+image
  thumbnail_4x3: https://via.placeholder.com/768x500?text=4x3
  thumbnail_1x1:  https://via.placeholder.com/768x768?text=1x1

# Collections
collections:
  projects:
    output: true
    layout: project
    permalink: /projects/:path/
  focuses:
    output: true
    layout: focus
    permalink: /focuses/:title/

# Build settings
safe: false
source: src

plugins:
  - jekyll-sitemap

_options:
  layout:
    hidden: true

statuses:
  - active
  - hidden
  - discontinued
  - graduated

stages:
  - 1. Design / Research
  - 2. Design / Solution Generation
  - 3. Design / Prototype
  - 4. Test / Pilot
  - 5. Test / Rigorous evaluation
  - 6. Scale